name: Pre-release check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: clang

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --build-config Release
