name: Release

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download antlr-4.13.1-complete.jar
        run: |
          wget https://www.antlr.org/download/antlr-4.13.1-complete.jar -P ${{github.workspace}}/tools/

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=20

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure

      - name: Install
        run: cmake --install ${{github.workspace}}/build --prefix install

      - name: Package
        run: cpack --config ${{github.workspace}}/build/CPackConfig.cmake

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./*.deb
